name: Deploy to staging environment

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ staging ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install dependencies
        run: npm install
      - name: Build the website
        run: npm run build
      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
        with:
          name: website-files
          path: './dist/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: website-files
          path: './dist/'
      - name: Deploy to staging environment
        run: |
          npm install --global surge
          surge  './dist/' 'systemctf.surge.sh' --token ${{secrets.surge_token}}
